### ISSUE TITLE
Properties with falsy values are not copied when using launchdarkly_project_copy

### ISSUE THREAD

**Issue by jonmort** [launchdarkly-labs/ansible-launchdarkly-collection#17]
**Is this a support request?**
No. PR incoming

**Describe the bug**
When copying a project using the ansible `launchdarkly_project_copy` properties in the API that have a Python Falsy value are not copied. This means that `offVariation` will not be set if it is 0

**To reproduce**
Create a feature flag with `offVariation` set to 0 and copy the project with the flag in it

**Expected behavior**
All properties for all flags should be copied

**Comment by InTheCloudDan** [comment]
closing issue.
