### ISSUE TITLE
includeInSnippet is not set when using launchdarkly_project_copy

### ISSUE THREAD

**Issue by jonmort** [launchdarkly-labs/ansible-launchdarkly-collection#21]
**Is this a support request?**
No. PR incoming

**Describe the bug**
`includeInSnippet` is not sent correctly when creating a feature flag via `launchdarkly_project_copy`

**To reproduce**
Set the `Make this flag available to client-side SDKs` flag to `true` for a feature flag and copy the project it is contained in.

**Expected behavior**
The `includeInSnippet` property of the flag should be set

**Comment by InTheCloudDan** [comment]
@jonmort I opened this PR based on yours and it should correctly fix the issue when I get it merged in and a new release pushed out: https://github.com/launchdarkly-labs/ansible-launchdarkly-collection/pull/20/files

I'll look to add more documentation around the feature, any suggestions on what aspects you see as missing would be helpful!

**Comment by jonmort** [comment]
Ah, super. I'll stand down.

If i'm being super selfish I would have liked some documentation that described step by step how to use this to copy a whole project from one LD account to another. The other thing that would be helpful to add is some comment about the intended use. What I mean is the use of `localhost` in the playbooks - is that how it should be used or just an example? Also it might be my Ansible knowledge lacking, but it would be helpful to see an example of how the lookup support works and how i could use it. Could I use it to make conditionally deploy infra for example?

**Comment by InTheCloudDan** [comment]
This is great feedback, thank you!

The `localhost` part is option for the user. They can run the playbook from their local machine or have it run remotely and as long as the variables are correct shouldn't be any difference to the module.

As it's still before a `1.0` release I'm planning to deprecate the `lookups` and move everything to a `_info` model. I asked about this in the Ansible Devs IRC after I got started on the collection and `lookups` are restricted to running on the host machine whereas `_info` modules are free-form and can be run from any machine without restriction. So in this use case there's nothing really that a lookup would offer over just a regular module.

That being said the `lookups` could be used to base infra depending on what is returned. If you're looking to feature flag the Infra you can look to use: https://launchdarkly-labs.github.io/ansible-launchdarkly-collection/modules/launchdarkly_variation_info.html

**Comment by jonmort** [comment]
Thanks for the info, helpful.

**Comment by InTheCloudDan** [comment]
closing issue.
